# -*- coding: utf-8 -*-
"""Third Year Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ofkm3JsNxb0MfKMG-lTXivQkgLLdUA0D
"""

from DataPreprocessing import FileExtraction, CSVManager
from ModelTrain import Training

import os

# change directory
os.chdir(r"D:\Third Year Project\CFIE-FRSE-master\output")

directory = os.getcwd()

csvManager = CSVManager("output.csv")

dp = FileExtraction(directory, csvManager.get_chosen_reports())

training = Training(dp.get_corpus(), csvManager.get_y())

'''
TODO:
    - Only extract texts into corpus that 14th column is equal to 1
        - do it by having an array of IDs extracted from the CSVManager
        - each time a text is added to corpus, increment the ID
        - when the temp_id has reached 3155 (the number of ids), stop
    - that way, there are gonna be 3155 reports (which will be converted to numerical)
        and 3155 y's => therefore able to be put into training model
'''

'''
train the model on the corpus, 
and then evaluate with combination of 
the numerical features (make a formula)
'''

# TODO:
    # Add bag of words